spring.application.name=feedback-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/feedback
spring.datasource.username=postgres
spring.datasource.password=Harika@2836
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
